-- MySQL Script generated by MySQL Workbench
-- sáb 13 dic 2014 19:30:58 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema liga_futbol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema liga_futbol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `liga_futbol` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `liga_futbol` ;

-- -----------------------------------------------------
-- Table `liga_futbol`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`equipos` (
  `nombre` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(20) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `visitante` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'true = visitante\nfalse = local',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`usuarios` (
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`posiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`posiciones` (
  `nombre_posicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_posicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`carreras` (
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`semestres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`semestres` (
  `semestre` INT NOT NULL,
  PRIMARY KEY (`semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`jugadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_posicion` VARCHAR(45) NOT NULL,
  `equipo` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `semestre` INT NOT NULL,
  `fotografia` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `app` VARCHAR(45) NOT NULL,
  `apm` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `created_at` DATETIME NOT NULL,
  `dorsal` VARCHAR(3) NOT NULL COMMENT 'Numero de playera.',
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `equipo`),
  INDEX `fk_jugadores_equipos1_idx` (`equipo` ASC),
  INDEX `fk_jugadores_posiciones1_idx` (`nombre_posicion` ASC),
  INDEX `fk_jugadores_carreras1_idx` (`carrera` ASC),
  INDEX `fk_jugadores_semestres1_idx` (`semestre` ASC),
  CONSTRAINT `fk_jugadores_equipos1`
    FOREIGN KEY (`equipo`)
    REFERENCES `liga_futbol`.`equipos` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugadores_posiciones1`
    FOREIGN KEY (`nombre_posicion`)
    REFERENCES `liga_futbol`.`posiciones` (`nombre_posicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugadores_carreras1`
    FOREIGN KEY (`carrera`)
    REFERENCES `liga_futbol`.`carreras` (`nombre_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugadores_semestres1`
    FOREIGN KEY (`semestre`)
    REFERENCES `liga_futbol`.`semestres` (`semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`tipos_torneos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`tipos_torneos` (
  `tipo_torneo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_torneo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`torneos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`torneos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_torneo` VARCHAR(45) NOT NULL,
  `fecha_torneo` DATE NOT NULL,
  `termino_torneo` DATE NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_torneos_tipos_torneos1_idx` (`tipo_torneo` ASC),
  CONSTRAINT `fk_torneos_tipos_torneos1`
    FOREIGN KEY (`tipo_torneo`)
    REFERENCES `liga_futbol`.`tipos_torneos` (`tipo_torneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`encuentros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`encuentros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `torneo_id` INT NOT NULL,
  `equipo1` VARCHAR(45) NOT NULL,
  `equipo2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_encuentros_equipos1_idx` (`equipo1` ASC),
  INDEX `fk_encuentros_equipos2_idx` (`equipo2` ASC),
  INDEX `fk_encuentros_torneos1_idx` (`torneo_id` ASC),
  CONSTRAINT `fk_encuentros_equipos1`
    FOREIGN KEY (`equipo1`)
    REFERENCES `liga_futbol`.`equipos` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuentros_equipos2`
    FOREIGN KEY (`equipo2`)
    REFERENCES `liga_futbol`.`equipos` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuentros_torneos1`
    FOREIGN KEY (`torneo_id`)
    REFERENCES `liga_futbol`.`torneos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`tabla_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`tabla_resultados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `encuentros_id` INT NOT NULL,
  `jugador_id` INT NOT NULL,
  `equipo_jugador` VARCHAR(45) NOT NULL,
  `goles` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tabla_resultados_encuentros1_idx` (`encuentros_id` ASC),
  INDEX `fk_tabla_resultados_jugadores1_idx` (`jugador_id` ASC, `equipo_jugador` ASC),
  CONSTRAINT `fk_tabla_resultados_encuentros1`
    FOREIGN KEY (`encuentros_id`)
    REFERENCES `liga_futbol`.`encuentros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabla_resultados_jugadores1`
    FOREIGN KEY (`jugador_id` , `equipo_jugador`)
    REFERENCES `liga_futbol`.`jugadores` (`id` , `equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`tipos_tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`tipos_tarjetas` (
  `tipo_tarjeta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`tipo_tarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liga_futbol`.`tarjetas_jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liga_futbol`.`tarjetas_jugadores` (
  `tabla_resultado_id` INT NOT NULL,
  `tipo_tarjeta` VARCHAR(10) NOT NULL,
  INDEX `fk_tarjetas_jugador_tabla_resultados1_idx` (`tabla_resultado_id` ASC),
  INDEX `fk_tarjetas_jugador_tipos_tarjetas1_idx` (`tipo_tarjeta` ASC),
  PRIMARY KEY (`tipo_tarjeta`, `tabla_resultado_id`),
  CONSTRAINT `fk_tarjetas_jugador_tabla_resultados1`
    FOREIGN KEY (`tabla_resultado_id`)
    REFERENCES `liga_futbol`.`tabla_resultados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjetas_jugador_tipos_tarjetas1`
    FOREIGN KEY (`tipo_tarjeta`)
    REFERENCES `liga_futbol`.`tipos_tarjetas` (`tipo_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
